//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SICORP-01\\SQLEXPRESS;Initial Catalog=Nutrovet;Persist Security Info=T" +
            "rue;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string NutrovetConnectionString {
            get {
                return ((string)(this["NutrovetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SICORP-01\\SQLEXPRESS;Initial Catalog=Nutrovet;Persist Security Info=T" +
            "rue;User ID=sa;Password=A1x291x0;MultipleActiveResultSets=True;Application Name=" +
            "EntityFramework")]
        public string NutrovetConnectionString1 {
            get {
                return ((string)(this["NutrovetConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9CLMC0P\\SQLEXPRESS;Initial Catalog=Nutrovet;Integrated Securi" +
            "ty=True")]
        public string NutrovetConnectionString2 {
            get {
                return ((string)(this["NutrovetConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sicorp-01\\sqlexpress;Initial Catalog=Nutrovet;Integrated Security=Tru" +
            "e")]
        public string NutrovetConnectionString3 {
            get {
                return ((string)(this["NutrovetConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sicorp-02\\sqlexpress;Initial Catalog=Nutrovet;Integrated Security=Tru" +
            "e")]
        public string NutrovetConnectionString4 {
            get {
                return ((string)(this["NutrovetConnectionString4"]));
            }
        }
    }
}
