//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be filled in!.
        /// </summary>
        internal static string CampoPreenchido {
            get {
                return ResourceManager.GetString("CampoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be selected!.
        /// </summary>
        internal static string CampoSelecionado {
            get {
                return ResourceManager.GetString("CampoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We identified that you are ALREADY our customer, but your Profile is BLOCKED! Contact the Administrator Via WhatsApp (61) 98136-6230!!!.
        /// </summary>
        internal static string ClienteExistAndBloq {
            get {
                return ResourceManager.GetString("ClienteExistAndBloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We identify that you are ALREADY our client! LOGIN and Renew your Plan Through your PROFILE SCREEN!!!.
        /// </summary>
        internal static string ClienteExistAndRenewPlan {
            get {
                return ResourceManager.GetString("ClienteExistAndRenewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name: {0} or email: {1} already exists in our registry, but the profile is BLOCKED. Contact the Administrator Via WhatsApp (61) 98136-6230!!!.
        /// </summary>
        internal static string ClienteOuMailExistAndBloqCP {
            get {
                return ResourceManager.GetString("ClienteOuMailExistAndBloqCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name: {0} or email: {1} already exists in our registry. LOGIN and Renew your Plan Through your PROFILE SCREEN..
        /// </summary>
        internal static string ClienteOuMailExistAndRenwePlanCP {
            get {
                return ResourceManager.GetString("ClienteOuMailExistAndRenwePlanCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with Purchase.
        /// </summary>
        internal static string CompraOk {
            get {
                return ResourceManager.GetString("CompraOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUNCTION.
        /// </summary>
        internal static string cpFuncao {
            get {
                return ResourceManager.GetString("cpFuncao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Data!.
        /// </summary>
        internal static string DadosValidos {
            get {
                return ResourceManager.GetString("DadosValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to perform the DELETION!!!.
        /// </summary>
        internal static string DeleteDenied {
            get {
                return ResourceManager.GetString("DeleteDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Completed Successfully!!!.
        /// </summary>
        internal static string DeleteOk {
            get {
                return ResourceManager.GetString("DeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to carry out Homologation!!!.
        /// </summary>
        internal static string HomologDenied {
            get {
                return ResourceManager.GetString("HomologDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOMOLOGATION completed successfully!!!.
        /// </summary>
        internal static string HomologOk {
            get {
                return ResourceManager.GetString("HomologOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform INSERT!!!.
        /// </summary>
        internal static string InsertDenied {
            get {
                return ResourceManager.GetString("InsertDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERTION Completed Successfully!!!.
        /// </summary>
        internal static string InsertOk {
            get {
                return ResourceManager.GetString("InsertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Record!!!.
        /// </summary>
        internal static string RegDuplicado {
            get {
                return ResourceManager.GetString("RegDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Reactivated!.
        /// </summary>
        internal static string RegReativado {
            get {
                return ResourceManager.GetString("RegReativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to make the CHANGE!!!.
        /// </summary>
        internal static string UpdateDenied {
            get {
                return ResourceManager.GetString("UpdateDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Successfully Made!!!.
        /// </summary>
        internal static string UpdateOk {
            get {
                return ResourceManager.GetString("UpdateOk", resourceCulture);
            }
        }
    }
}
