//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acessos
    {
        public int IdPessoa { get; set; }
        public int IdAcFunc { get; set; }
        public Nullable<bool> Inserir { get; set; }
        public Nullable<bool> Alterar { get; set; }
        public Nullable<bool> Excluir { get; set; }
        public Nullable<bool> Consultar { get; set; }
        public Nullable<bool> AcoesEspeciais { get; set; }
        public Nullable<bool> Relatorios { get; set; }
        public Nullable<bool> SuperUser { get; set; }
        public Nullable<bool> TermoUso { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AcessosAuxFuncoes AcessosAuxFuncoes { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
