//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessosVigenciaPlanos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcessosVigenciaPlanos()
        {
            this.AcessosVigenciaSituacao = new HashSet<AcessosVigenciaSituacao>();
        }
    
        public int IdPessoa { get; set; }
        public int IdVigencia { get; set; }
        public int IdPlano { get; set; }
        public string IdSubscriptionPagarMe { get; set; }
        public string StatusPagarMe { get; set; }
        public System.DateTime DtInicial { get; set; }
        public System.DateTime DtFinal { get; set; }
        public Nullable<int> IdCartao { get; set; }
        public Nullable<int> IdCupom { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AcessosVigenciaCupomDesconto AcessosVigenciaCupomDesconto { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        public virtual PessoasCartaoCredito PessoasCartaoCredito { get; set; }
        public virtual PlanosAssinaturas PlanosAssinaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcessosVigenciaSituacao> AcessosVigenciaSituacao { get; set; }
    }
}
