//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessosVigenciaSituacao
    {
        public int IdVigencia { get; set; }
        public int IdVigSit { get; set; }
        public int IdSituacao { get; set; }
        public Nullable<System.DateTime> DataSituacao { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AcessosVigenciaPlanos AcessosVigenciaPlanos { get; set; }
    }
}
