//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessosVigenciaCupomDesconto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcessosVigenciaCupomDesconto()
        {
            this.AcessosVigenciaPlanos = new HashSet<AcessosVigenciaPlanos>();
        }
    
        public int IdCupom { get; set; }
        public string NrCumpom { get; set; }
        public Nullable<int> dPlanoTp { get; set; }
        public System.DateTime DtInicial { get; set; }
        public System.DateTime DtFinal { get; set; }
        public Nullable<bool> fUsado { get; set; }
        public Nullable<bool> fAcessoLiberado { get; set; }
        public string Professor { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcessosVigenciaPlanos> AcessosVigenciaPlanos { get; set; }
    }
}
