//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alimentos()
        {
            this.AlimentoNutrientes = new HashSet<AlimentoNutrientes>();
            this.AlimentosAuxAlias = new HashSet<AlimentosAuxAlias>();
            this.CardapiosAlimentos = new HashSet<CardapiosAlimentos>();
            this.DietasAlimentos = new HashSet<DietasAlimentos>();
        }
    
        public Nullable<int> IdPessoa { get; set; }
        public int IdAlimento { get; set; }
        public int IdGrupo { get; set; }
        public int IdFonte { get; set; }
        public Nullable<int> IdCateg { get; set; }
        public Nullable<int> NDB_No { get; set; }
        public string Alimento { get; set; }
        public Nullable<bool> Compartilhar { get; set; }
        public Nullable<bool> fHomologado { get; set; }
        public Nullable<bool> fAlias { get; set; }
        public Nullable<System.DateTime> DataHomol { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlimentoNutrientes> AlimentoNutrientes { get; set; }
        public virtual AlimentosAuxCategorias AlimentosAuxCategorias { get; set; }
        public virtual AlimentosAuxFontes AlimentosAuxFontes { get; set; }
        public virtual AlimentosAuxGrupos AlimentosAuxGrupos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlimentosAuxAlias> AlimentosAuxAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardapiosAlimentos> CardapiosAlimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietasAlimentos> DietasAlimentos { get; set; }
    }
}
