//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimaisAuxRacas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimaisAuxRacas()
        {
            this.Animais = new HashSet<Animais>();
        }
    
        public int IdEspecie { get; set; }
        public int IdRaca { get; set; }
        public string Raca { get; set; }
        public Nullable<int> IdadeAdulta { get; set; }
        public Nullable<int> CrescInicial { get; set; }
        public Nullable<int> CrescFinal { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animais> Animais { get; set; }
        public virtual AnimaisAuxEspecies AnimaisAuxEspecies { get; set; }
    }
}
