//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biblioteca
    {
        public int IdBiblio { get; set; }
        public Nullable<int> IdSecao { get; set; }
        public string NomeArq { get; set; }
        public string Descricao { get; set; }
        public string Autor { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Caminho { get; set; }
        public Nullable<int> Ordenador { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual BibliotecaAuxSecoes BibliotecaAuxSecoes { get; set; }
    }
}
