//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cardapio()
        {
            this.Cardapio1 = new HashSet<Cardapio>();
            this.CardapiosAlimentos = new HashSet<CardapiosAlimentos>();
            this.Receituario = new HashSet<Receituario>();
        }
    
        public int IdPessoa { get; set; }
        public Nullable<int> IdAnimal { get; set; }
        public int IdCardapio { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DtCardapio { get; set; }
        public Nullable<decimal> FatorEnergia { get; set; }
        public Nullable<decimal> NEM { get; set; }
        public Nullable<bool> Gestante { get; set; }
        public Nullable<bool> Lactante { get; set; }
        public Nullable<int> LactacaoSemanas { get; set; }
        public Nullable<int> NrFilhotes { get; set; }
        public Nullable<int> IdDieta { get; set; }
        public Nullable<decimal> EmCardapio { get; set; }
        public Nullable<int> NrCardapio { get; set; }
        public string Arquivo { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> IdCardCopia { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Animais Animais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardapio> Cardapio1 { get; set; }
        public virtual Cardapio Cardapio2 { get; set; }
        public virtual Dietas Dietas { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardapiosAlimentos> CardapiosAlimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receituario> Receituario { get; set; }
    }
}
