//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigReceituario
    {
        public int IdPessoa { get; set; }
        public Nullable<System.DateTime> DtIniUso { get; set; }
        public string NomeClinica { get; set; }
        public string Slogan { get; set; }
        public Nullable<bool> fLivreCabecalho { get; set; }
        public string LivreCabecalho { get; set; }
        public Nullable<bool> fLivreRodape { get; set; }
        public string LivreRodape { get; set; }
        public string Site { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Logotipo { get; set; }
        public string Assinatura { get; set; }
        public string CRMV { get; set; }
        public string CrmvUf { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Logradouro { get; set; }
        public string Logr_Nr { get; set; }
        public string Logr_Compl { get; set; }
        public string Logr_Bairro { get; set; }
        public string Logr_CEP { get; set; }
        public string Logr_Cidade { get; set; }
        public string Logr_UF { get; set; }
        public string Logr_Pais { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
