//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietasAlimentos
    {
        public int IdDieta { get; set; }
        public int IdDietaAlim { get; set; }
        public int IdAlimento { get; set; }
        public int IdTpIndicacao { get; set; }
        public Nullable<decimal> Quant { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Alimentos Alimentos { get; set; }
        public virtual Dietas Dietas { get; set; }
    }
}
