//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dietas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dietas()
        {
            this.Cardapio = new HashSet<Cardapio>();
            this.DietasAlimentos = new HashSet<DietasAlimentos>();
            this.NutraceuticosDietas = new HashSet<NutraceuticosDietas>();
        }
    
        public Nullable<int> IdEspecie { get; set; }
        public int IdDieta { get; set; }
        public string Dieta { get; set; }
        public Nullable<decimal> Carboidrato { get; set; }
        public Nullable<decimal> Proteina { get; set; }
        public Nullable<decimal> Gordura { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AnimaisAuxEspecies AnimaisAuxEspecies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardapio> Cardapio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietasAlimentos> DietasAlimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutraceuticosDietas> NutraceuticosDietas { get; set; }
    }
}
