//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExigenciasNutricionais
    {
        public int IdExigNutr { get; set; }
        public int IdTabNutr { get; set; }
        public int IdEspecie { get; set; }
        public int IdIndic { get; set; }
        public Nullable<int> IdTpValor { get; set; }
        public int IdNutr1 { get; set; }
        public Nullable<int> IdUnidade1 { get; set; }
        public Nullable<decimal> Proporcao1 { get; set; }
        public Nullable<decimal> Valor1 { get; set; }
        public Nullable<int> IdNutr2 { get; set; }
        public Nullable<int> IdUnidade2 { get; set; }
        public Nullable<decimal> Proporcao2 { get; set; }
        public Nullable<decimal> Valor2 { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AnimaisAuxEspecies AnimaisAuxEspecies { get; set; }
        public virtual ExigenciasNutrAuxIndicacoes ExigenciasNutrAuxIndicacoes { get; set; }
        public virtual Nutrientes Nutrientes { get; set; }
        public virtual Nutrientes Nutrientes1 { get; set; }
    }
}
