//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsSistema
    {
        public Nullable<int> IdPessoa { get; set; }
        public int IdLog { get; set; }
        public Nullable<int> IdTabela { get; set; }
        public Nullable<int> IdAcao { get; set; }
        public string Mensagem { get; set; }
        public string Justificativa { get; set; }
        public Nullable<System.DateTime> Datahora { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
