//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutrovetEntities : DbContext
    {
        public NutrovetEntities()
            : base(Conexao.StrCon())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acessos> Acessos { get; set; }
        public virtual DbSet<AcessosAuxFuncoes> AcessosAuxFuncoes { get; set; }
        public virtual DbSet<AcessosAuxTelas> AcessosAuxTelas { get; set; }
        public virtual DbSet<AcessosFuncoesTelas> AcessosFuncoesTelas { get; set; }
        public virtual DbSet<AcessosVigenciaCupomDesconto> AcessosVigenciaCupomDesconto { get; set; }
        public virtual DbSet<AcessosVigenciaPlanos> AcessosVigenciaPlanos { get; set; }
        public virtual DbSet<AcessosVigenciaSituacao> AcessosVigenciaSituacao { get; set; }
        public virtual DbSet<AlimentoNutrientes> AlimentoNutrientes { get; set; }
        public virtual DbSet<Alimentos> Alimentos { get; set; }
        public virtual DbSet<AlimentosAuxAlias> AlimentosAuxAlias { get; set; }
        public virtual DbSet<AlimentosAuxCategorias> AlimentosAuxCategorias { get; set; }
        public virtual DbSet<AlimentosAuxFontes> AlimentosAuxFontes { get; set; }
        public virtual DbSet<AlimentosAuxGrupos> AlimentosAuxGrupos { get; set; }
        public virtual DbSet<Animais> Animais { get; set; }
        public virtual DbSet<AnimaisAuxEspecies> AnimaisAuxEspecies { get; set; }
        public virtual DbSet<AnimaisAuxRacas> AnimaisAuxRacas { get; set; }
        public virtual DbSet<AnimaisPesoHistorico> AnimaisPesoHistorico { get; set; }
        public virtual DbSet<Biblioteca> Biblioteca { get; set; }
        public virtual DbSet<BibliotecaAuxSecoes> BibliotecaAuxSecoes { get; set; }
        public virtual DbSet<Cardapio> Cardapio { get; set; }
        public virtual DbSet<CardapiosAlimentos> CardapiosAlimentos { get; set; }
        public virtual DbSet<ConfigReceituario> ConfigReceituario { get; set; }
        public virtual DbSet<Dietas> Dietas { get; set; }
        public virtual DbSet<DietasAlimentos> DietasAlimentos { get; set; }
        public virtual DbSet<ExigenciasNutrAuxIndicacoes> ExigenciasNutrAuxIndicacoes { get; set; }
        public virtual DbSet<ExigenciasNutricionais> ExigenciasNutricionais { get; set; }
        public virtual DbSet<LogsSistema> LogsSistema { get; set; }
        public virtual DbSet<Nutraceuticos> Nutraceuticos { get; set; }
        public virtual DbSet<NutraceuticosDietas> NutraceuticosDietas { get; set; }
        public virtual DbSet<Nutrientes> Nutrientes { get; set; }
        public virtual DbSet<NutrientesAuxGrupos> NutrientesAuxGrupos { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<PessoasCartaoCredito> PessoasCartaoCredito { get; set; }
        public virtual DbSet<PessoasDocumentos> PessoasDocumentos { get; set; }
        public virtual DbSet<PlanosAssinaturas> PlanosAssinaturas { get; set; }
        public virtual DbSet<PortalContato> PortalContato { get; set; }
        public virtual DbSet<PrescricaoAuxTipos> PrescricaoAuxTipos { get; set; }
        public virtual DbSet<Receituario> Receituario { get; set; }
        public virtual DbSet<ReceituarioNutrientes> ReceituarioNutrientes { get; set; }
        public virtual DbSet<Tutores> Tutores { get; set; }
    }
}
