//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutraceuticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nutraceuticos()
        {
            this.NutraceuticosDietas = new HashSet<NutraceuticosDietas>();
        }
    
        public int IdNutrac { get; set; }
        public int IdEspecie { get; set; }
        public int IdNutr { get; set; }
        public Nullable<decimal> DoseMin { get; set; }
        public Nullable<int> IdUnidMin { get; set; }
        public Nullable<decimal> DoseMax { get; set; }
        public Nullable<int> IdUnidMax { get; set; }
        public Nullable<int> IdPrescr1 { get; set; }
        public Nullable<int> IdPrescr2 { get; set; }
        public string Obs { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual AnimaisAuxEspecies AnimaisAuxEspecies { get; set; }
        public virtual Nutrientes Nutrientes { get; set; }
        public virtual PrescricaoAuxTipos PrescricaoAuxTipos { get; set; }
        public virtual PrescricaoAuxTipos PrescricaoAuxTipos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutraceuticosDietas> NutraceuticosDietas { get; set; }
    }
}
