//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoas()
        {
            this.AcessosVigenciaPlanos = new HashSet<AcessosVigenciaPlanos>();
            this.Alimentos = new HashSet<Alimentos>();
            this.AlimentosAuxAlias = new HashSet<AlimentosAuxAlias>();
            this.Cardapio = new HashSet<Cardapio>();
            this.LogsSistema = new HashSet<LogsSistema>();
            this.PessoasCartaoCredito = new HashSet<PessoasCartaoCredito>();
            this.PessoasDocumentos1 = new HashSet<PessoasDocumentos>();
            this.Tutores = new HashSet<Tutores>();
            this.Tutores1 = new HashSet<Tutores>();
        }
    
        public int IdPessoa { get; set; }
        public int IdTpPessoa { get; set; }
        public string Nome { get; set; }
        public Nullable<int> dTpEntidade { get; set; }
        public Nullable<int> dNacionalidade { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string Passaporte { get; set; }
        public string DocumentosOutros { get; set; }
        public Nullable<int> CRVM { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Logotipo { get; set; }
        public string Assinatura { get; set; }
        public string Logradouro { get; set; }
        public string Logr_Nr { get; set; }
        public string Logr_Compl { get; set; }
        public string Logr_Bairro { get; set; }
        public string Logr_CEP { get; set; }
        public string Logr_Cidade { get; set; }
        public string Logr_UF { get; set; }
        public string Logr_Pais { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Acessos Acessos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcessosVigenciaPlanos> AcessosVigenciaPlanos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alimentos> Alimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlimentosAuxAlias> AlimentosAuxAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardapio> Cardapio { get; set; }
        public virtual ConfigReceituario ConfigReceituario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsSistema> LogsSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasCartaoCredito> PessoasCartaoCredito { get; set; }
        public virtual PessoasDocumentos PessoasDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasDocumentos> PessoasDocumentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutores> Tutores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutores> Tutores1 { get; set; }
    }
}
