//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanosAssinaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanosAssinaturas()
        {
            this.AcessosVigenciaPlanos = new HashSet<AcessosVigenciaPlanos>();
        }
    
        public int IdPlano { get; set; }
        public Nullable<int> IdPlanoPagarMe { get; set; }
        public Nullable<int> IdPlanoPagarMeTestes { get; set; }
        public int dNomePlano { get; set; }
        public Nullable<decimal> ValorPlano { get; set; }
        public int dPlanoTp { get; set; }
        public int dPeriodo { get; set; }
        public Nullable<int> QtdAnimais { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcessosVigenciaPlanos> AcessosVigenciaPlanos { get; set; }
    }
}
