//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalContato
    {
        public int IdContato { get; set; }
        public string NomeContato { get; set; }
        public string EmailContato { get; set; }
        public string Assunto { get; set; }
        public string Mensagem { get; set; }
        public Nullable<System.DateTime> DataEnvio { get; set; }
        public Nullable<int> MsgSituacao { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
        public string Observacoes { get; set; }
        public byte[] Versao { get; set; }
    }
}
