//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescricaoAuxTipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrescricaoAuxTipos()
        {
            this.Nutraceuticos = new HashSet<Nutraceuticos>();
            this.Nutraceuticos1 = new HashSet<Nutraceuticos>();
            this.ReceituarioNutrientes = new HashSet<ReceituarioNutrientes>();
            this.ReceituarioNutrientes1 = new HashSet<ReceituarioNutrientes>();
            this.ReceituarioNutrientes2 = new HashSet<ReceituarioNutrientes>();
        }
    
        public int IdPrescr { get; set; }
        public string Prescricao { get; set; }
        public string Intervalo { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutraceuticos> Nutraceuticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutraceuticos> Nutraceuticos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceituarioNutrientes> ReceituarioNutrientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceituarioNutrientes> ReceituarioNutrientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceituarioNutrientes> ReceituarioNutrientes2 { get; set; }
    }
}
