//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receituario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receituario()
        {
            this.ReceituarioNutrientes = new HashSet<ReceituarioNutrientes>();
        }
    
        public int IdCardapio { get; set; }
        public int IdReceita { get; set; }
        public int dTpRec { get; set; }
        public string Titulo { get; set; }
        public string Veiculo { get; set; }
        public string QuantVeic { get; set; }
        public string Posologia { get; set; }
        public string VeiculoSid { get; set; }
        public string QuantVeicSid { get; set; }
        public string PosologiaSid { get; set; }
        public string VeiculoTid { get; set; }
        public string QuantVeicTid { get; set; }
        public string PosologiaTid { get; set; }
        public string Prescricao { get; set; }
        public string InstrucoesReceita { get; set; }
        public Nullable<System.DateTime> DataReceita { get; set; }
        public string LocalReceita { get; set; }
        public Nullable<int> dTblExigNutr { get; set; }
        public Nullable<int> QuantDietas { get; set; }
        public string Observacao { get; set; }
        public string Arquivo { get; set; }
        public string NrReceita { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public byte[] Versao { get; set; }
    
        public virtual Cardapio Cardapio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceituarioNutrientes> ReceituarioNutrientes { get; set; }
    }
}
