/*
Deployment script for nutrovet1

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO

PRINT N'Dropping [dbo].[AcessosVigenciaCupomDesconto].[FK_AcessosVigenciaCupomDesconto_1]...';


GO
DROP INDEX [FK_AcessosVigenciaCupomDesconto_1]
    ON [dbo].[AcessosVigenciaCupomDesconto];


GO
PRINT N'Dropping [dbo].[AcessosVigenciaCupomDesconto].[IX_AcessosVigenciaCupomDesconto_1]...';


GO
DROP INDEX [IX_AcessosVigenciaCupomDesconto_1]
    ON [dbo].[AcessosVigenciaCupomDesconto];


GO
PRINT N'Dropping [dbo].[FK_AcessosVigenciaCupomDesconto_AcessosVigenciaPlanos]...';


GO
ALTER TABLE [dbo].[AcessosVigenciaCupomDesconto] DROP CONSTRAINT [FK_AcessosVigenciaCupomDesconto_AcessosVigenciaPlanos];


GO
PRINT N'Dropping [dbo].[IX_AcessosVigenciaCupomDesconto]...';


GO
ALTER TABLE [dbo].[AcessosVigenciaCupomDesconto] DROP CONSTRAINT [IX_AcessosVigenciaCupomDesconto];


GO
PRINT N'Altering [dbo].[AcessosVigenciaCupomDesconto]...';


GO
ALTER TABLE [dbo].[AcessosVigenciaCupomDesconto] DROP COLUMN [IdVigencia];


GO
PRINT N'Creating [dbo].[IX_AcessosVigenciaCupomDesconto]...';


GO
ALTER TABLE [dbo].[AcessosVigenciaCupomDesconto]
    ADD CONSTRAINT [IX_AcessosVigenciaCupomDesconto] UNIQUE NONCLUSTERED ([NrCumpom] ASC);


GO
PRINT N'Creating [dbo].[Pessoas].[FK_Pessoas_1]...';


GO
CREATE NONCLUSTERED INDEX [FK_Pessoas_1]
    ON [dbo].[Pessoas]([IdTpPessoa] ASC);


GO
PRINT N'Creating [dbo].[Pessoas].[IX_Pessoas_1]...';


GO
CREATE NONCLUSTERED INDEX [IX_Pessoas_1]
    ON [dbo].[Pessoas]([Email] ASC);


GO
PRINT N'Update complete.';


GO
